# -*- ruby -*-

require 'rubygems'
require 'hoe'

Hoe.spec 'self-ml' do
  developer('Indigo Casson', 'atamiser@gmail.com')

  # self.rubyforge_name = 'Rubyx' # if different than 'Ruby'
end

# vim: syntax=ruby
